# Generated by Django 4.2.30 on 2026-04-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Original URL from RSS feed', max_length=2048)),
                ('canonical_url', models.URLField(max_length=2048, unique=True)),
                ('url_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('pub_date', models.DateTimeField(db_index=True)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('reading_time', models.PositiveSmallIntegerField(blank=True, help_text='Minutes', null=True)),
                ('lead_image_url', models.URLField(blank=True, max_length=2048)),
                ('status', models.CharField(choices=[('RAW', 'Raw'), ('ENRICHED', 'Enriched'), ('ENRICH_FAILED', 'Enrich Failed')], db_index=True, default='RAW', max_length=20)),
                ('enrich_error', models.TextField(blank=True)),
                ('enrich_attempts', models.PositiveSmallIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='feeds.source')),
            ],
            options={
                'ordering': ['-pub_date'],
                'indexes': [models.Index(fields=['source', '-pub_date'], name='articles_ar_source__33f238_idx'), models.Index(fields=['status'], name='articles_ar_status_edb746_idx'), models.Index(fields=['-pub_date'], name='articles_ar_pub_dat_5d5d91_idx')],
            },
        ),
    ]
