# Generated by Django 4.2.30 on 2026-04-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="categories",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
