# Generated by Django 4.2.30 on 2026-04-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('rss_url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('fetch_interval', models.PositiveIntegerField(default=60, help_text='Minutes between fetches')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('items_new', models.PositiveIntegerField(default=0)),
                ('items_stored', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='feeds.source')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['source', '-fetched_at'], name='feeds_fetch_source__5c777b_idx')],
            },
        ),
    ]
